# ╭─────────────────────────────────ImplementationGuide-fish.json──────────────────────────────────╮
# │  The properties below are used to create the ImplementationGuide resource. For a list of       │
# │  supported properties, see:                                                                    │
# │  https://fshschool.org/docs/sushi/configuration/#full-configuration                            │
# ╰────────────────────────────────────────────────────────────────────────────────────────────────╯
id: medcom.fhir.dk.hospitalnotificationtestscripts
canonical: http://medcomfhir.dk/ig/hospitalnotificationtestscripts 
version: 3.0.1
name: HospitalNotification Testscripts
title: HospitalNotification Testscripts
status: active
publisher: MedCom
contact:
  - name: MedCom
    telecom:
      - system: email
        value: "mailto:fhir@medcom.dk"
description: Testscripts for HospitalNotification v. 3.0.1
license: CC0-1.0
fhirVersion: 4.0.1
parameters:
  apply-publisher: true
  apply-contact: true
  show-inherited-invariants: false
copyrightYear: 2020+
releaseLabel: ci-build
dependencies: 
  medcom.fhir.dk.hospitalnotification: 
    uri: http://medcomfhir.dk/ig/hospitalnotification/ImplementationGuide/medcom.fhir.dk.hospitalnotification
    version: current
#  net.aegis.touchstone.fhir.testing:
#    uri: 'http://touchstone.aegis.net/touchstone/fhir/testing/ImplementationGuide/net.aegis.touchstone.touchstone.fhir.testing'
#    version: 1.6.0


# ╭────────────────────────────────────────────menu.xml────────────────────────────────────────────╮
# │  To use a provided input/includes/menu.xml file, delete the "menu" property below.             │
# ╰────────────────────────────────────────────────────────────────────────────────────────────────╯
menu:
  IG Home: index.html
  Test scripts: testscripts.html
  Test examples: testexamples.html
  Artifacts Summary: artifacts.html
  Download: downloads.html



# The resources property corresponds to IG.definition.resource.
# SUSHI can auto-generate all of the resource entries based on
# the FSH definitions and/or information in any user-provided
# JSON or XML resource files. If the generated entries are not
# sufficient or complete, however, the author can add entries
# here. If the reference matches a generated entry, it will
# replace the generated entry. If it doesn't match any generated
# entries, it will be added to the generated entries. The format
# follows IG.definition.resource with the following differences:
#   * use IG.definition.resource.reference.reference as the YAML key.
#   * if the key is an id or name, SUSHI will replace it with the
#     correct URL when generating the IG JSON.
#   * specify "omit" to omit a FSH-generated resource from the
#     resource list.
#   * if the exampleCanonical is an id or name, SUSHI will replace
#     it with the correct canonical when generating the IG JSON.
#   * groupingId can be used, but top-level groups syntax may be a
#     better option (see below).
# The following are simple examples to demonstrate what this might
# look like:
#
#resources:
#  Binary/create-STIN-01: 
#    extension:
#    - url: http://hl7.org/fhir/StructureDefinition/implementationguide-resource-format
#      valueCode: application/fhir+json
#    name: STIN-01
#    exampleCanonical: http://medcomfhir.dk/ig/hospitalnotification/StructureDefinition/medcom-hospitalNotification-message
